[[main]]
  name = "ğŸ† Podiums"
  url = "/"
  weight = 5

[[main]]
  name = "ğŸ“œ PrÃ©sentation"
  url = "/presentation/"
  weight = 10

[[main]]
  name = "ğŸ¥‡ Tournois Duels"
  url = "/tournois/"
  identifier = "tournois"
  weight = 15

[[main]]
  name = "RÃ¨gles"
  url = "/tournois/Regles"
  parent = "tournois"
  weight = 16

[[main]]
  name = "Tournoi 24-25 #1"
  url = "/tournois/24-25/01"
  parent = "tournois"
  weight = 17

[[main]]
  name = "Tournoi 24-25 #2"
  url = "/tournois/24-25/02"
  parent = "tournois"
  weight = 17

[[main]]
  name = "Tournoi 24-25 #3"
  url = "/tournois/24-25/03"
  parent = "tournois"
  weight = 17

[[main]]
  name = "ğŸ RÃ©sultats"
  url = "/resultats/classements/"
  identifier = "resultats"
  weight = 25

[[main]]
  name = "Classement F/A-18C"
  weight = 30
  pre = "f-18-h"
  url = "/resultats/classements/classement_fa18c"
  parent = "resultats"

[[main]]
  name = "Classement M-2000C"
  weight = 40
  pre = "M2000-h"
  url = "/resultats/classements/classement_m2000c"
  parent = "resultats"

[[main]]
  name = "Classement F-14B"
  weight = 50
  pre = "f-14-h"
  url = "/resultats/classements/classement_f14b"
  parent = "resultats"

[[main]]
  name = "Classement F-16C Block50"
  weight = 60
  pre = "f-16-h"
  url = "/resultats/classements/classement_f16c50"
  parent = "resultats"

[[main]]
  name = "Classement F-15E"
  weight = 65
  pre = "f-15-h"
  url = "/resultats/classements/classement_f15e"
  parent = "resultats"

[[main]]
  name = "Classement AV8B"
  weight = 70
  pre = "av8b-h"
  url = "/resultats/classements/classement_av8b"
  parent = "resultats"

[[main]]
  name = "Classement JF-17"
  weight = 80
  pre = "jf-17-h"
  url = "/resultats/classements/classement_jf17"
  parent = "resultats"

[[main]]
  name = "Classement Mirage F1-EE"
  weight = 90
  pre = "mf1-h"
  url = "/resultats/classements/classement_miragef1ee"
  parent = "resultats"

[[main]]
  name = "Classement F-4E"
  weight = 90
  pre = "f-4-h"
  url = "/resultats/classements/classement_f4e"
  parent = "resultats"

[[main]]
  name = "Classement MiG-21Bis"
  weight = 100
  pre = "mig21-h"
  url = "/resultats/classements/classement_MiG_21Bis"
  parent = "resultats"

[[main]]
  name = "Classement Su-27"
  weight = 105
  pre = "su27-h"
  url = "/resultats/classements/classement_su27"
  parent = "resultats"

[[main]]
  name = "â±ï¸ Tous les chronos"
  weight = 110
  pre = ""
  url = "/resultats/classements/tous_les_chronos"
  parent = "resultats"

[[resultats]]
  name = "Classements"
  weight = 2
  identifier = "classements"
  url = "/resultats/classements/"


[[footer2]]
  name = "ELO Dogfight"
  url = "https://elodogfight.cellules-rapaces.fr"
  weight = 10

[[footer2]]
  name = "Tanker Party"
  url = "https://tankerparty.cellules-rapaces.fr"
  weight = 20

[[footer2]]
  name = "Dagger One"
  url = "https://dagger-one.cellules-rapaces.fr"
  weight = 30

[[footer3]]
  name = "Cellules Rapaces"
  url = "https://www.cellules-rapaces.fr"
  weight = 10

[[footer3]]
  name = "Contact"
  url = "/contact/"
  weight = 20

[[footer3]]
  name = "Mentions lÃ©gales"
  url = "/mentionslegales/"
  weight = 30
